#ifndef RESOURCE_H
#define RESOURCE_H

#define IDI_ICON1 101
#define IDB_FOLDER_ICON 102
#define IDB_NOEXIST_ICON 103
#define IDB_TOPMOST_SELECTED 104
#define IDB_TOPMOST_UNSELECTED 105
#define IDB_TEXT_ICON 106
#define IDB_NET_ICON 107
#define IDB_MAIL_ICON 108
#define IDB_APP_ICON 109

#endif
